-- Kulam Heritage — Supabase schema (run in the Supabase SQL editor).
-- Public read access; writes restricted to authenticated admins.

-- ---------- KULAMS (reference data: surname → gothram → kula deivam) ----------
create table if not exists public.kulams (
  id          bigint generated by default as identity primary key,
  surname     text not null,          -- inti peru
  house       text,                   -- house name
  gothram     text,
  kuladeivam  text,                   -- family deity / temple
  place       text,
  lat         double precision,       -- to be geocoded later
  lng         double precision,
  created_at  timestamptz default now()
);
create index if not exists kulams_surname_idx on public.kulams using gin (to_tsvector('simple', coalesce(surname,'') || ' ' || coalesce(gothram,'') || ' ' || coalesce(place,'')));

-- ---------- VENUES (kalyana mandapams) ----------
create table if not exists public.venues (
  id            bigint generated by default as identity primary key,
  name          text not null,
  area          text,
  district      text,
  lat           double precision,
  lng           double precision,
  capacity_min  int,
  capacity_max  int,
  plate_veg     int,
  plate_nonveg  int,
  ac            boolean default false,
  phone         text,
  created_at    timestamptz default now()
);
create index if not exists venues_district_idx on public.venues (district);

-- ---------- VENDORS (photographers, planners, caterers, silk, etc.) ----------
create table if not exists public.vendors (
  id          bigint generated by default as identity primary key,
  category    text not null,          -- 'photographer' | 'planner' | 'caterer' | 'decor' | 'makeup' | 'silk' | 'jewellery' | 'music' | 'invites' | 'returngifts'
  name        text not null,
  area        text,
  district    text,
  phone       text,
  price_info  text,
  note        text,
  created_at  timestamptz default now()
);
create index if not exists vendors_category_idx on public.vendors (category);

-- ---------- Row Level Security ----------
alter table public.kulams  enable row level security;
alter table public.venues  enable row level security;
alter table public.vendors enable row level security;

-- Everyone can read.
create policy "public read kulams"  on public.kulams  for select using (true);
create policy "public read venues"  on public.venues  for select using (true);
create policy "public read vendors" on public.vendors for select using (true);

-- Only signed-in users (admins) can write. Tighten later to an admin role/email.
create policy "auth write kulams"  on public.kulams  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "auth write venues"  on public.venues  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "auth write vendors" on public.vendors for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
