-- Seed the kulams table. Paste this into the Supabase SQL editor AFTER running schema.sql.
-- Safe to run more than once (existing ids are skipped).

insert into public.kulams (id, surname, house, gothram, kuladeivam, place) values
  (1, 'Aarer', 'Aare', 'Yenulla, Yelpunulla', 'Devara kovil', 'Erichinapati (Pallapati)'),
  (2, 'Aarikatlaar', 'Arikatla', 'Palulla, Cherukunulla, Selukoori', 'Devara kovil', 'Chinnametupaalayam'),
  (3, 'Aarikattalaar', null, null, 'Guruvammal Gurusaami Konammal kovil', 'Ammapatti'),
  (4, 'Aavula maarthar', 'Avula', 'Ponnuri, Pogunulla', 'Angaala Parameshwari kovil', 'Palladam'),
  (5, 'Adugullar', null, null, 'Aevara kovil', 'Ayyampati, Aravakurichi'),
  (6, 'Angalakuricher', 'Angalakuduru', 'Maadhalla', 'Mangammal Beddhakka kovil', 'Kaanur, Pudur'),
  (7, 'Anumoloorar', 'Anumlu', 'Eesalla', 'Konammal kovil', 'Madoorampatti'),
  (8, 'Beemannar', 'Bheemananeni', 'Marutla, Pamidipalla', 'Naagammal kovil', 'Thaarapuram, Uppar Arugil'),
  (9, 'Chandragiriyaar', 'Chandragiri', 'Pognulla, Pongunoola', 'Lakshmi ammal kovil', 'Aavarampaalayam'),
  (10, 'Chennai', 'Chennupati', 'Pogunulla, Pasupu neela', 'Konammal kovil', 'Idikarei'),
  (11, 'Dharmapuriyaar', 'dharmapuram', 'Vipparla, Punugoti Valoottal', 'Ruthrammal Kovil', 'Viyampaalayam'),
  (12, 'Dhivyaar, Pejavaadiyaar', null, null, 'Naagammal kovil', 'Thaarapuram, Uppar Arugil'),
  (13, 'Edugullar', null, null, 'Ellammal kovil', 'Kongappatti, Attanchathiram'),
  (14, 'Edugullar', null, null, 'Devara kovil', 'Kothappaalayam (Aravei)'),
  (15, 'Edugullar', null, null, 'Devara kovil', 'Poolakkampatti'),
  (16, 'Eendalaar', null, 'Noonavalli', 'Devara kovil', 'Ammapatti'),
  (17, 'Eeramanjar', 'Veeramachneni', 'Mangapuri', 'Matthamma Govindammal kovil', 'Devanampalayam'),
  (18, 'Eelamaar', null, null, null, 'Naranaapuram'),
  (19, 'Eminnar', 'Yemineni', 'Janakanulla', 'Sri Renuka Ellammal kovil', 'Dalamarathupati, Karor vattam'),
  (20, 'Endapillaar', 'Yendapalli', 'Kundhitla', 'Endammal Mathraalammal kovil', 'Uppilipaalayam'),
  (21, 'Enukundaar', null, null, 'Devara kovil', 'Poolankinaru (udumalai)'),
  (22, 'Enukundaar', null, 'Inakandi', 'Endammal kovil', 'Komangalam'),
  (23, 'Enukundaar, Pocchinnar', null, null, 'Poodhaatiyaar kovil', 'Komangalam'),
  (24, 'Eravandaar', null, 'Thalluri', 'Endammal China Endammal Kasthurinayurdu kovil', 'Pongaloor'),
  (25, 'Erivinnar', null, 'Thalluri', 'Beddhakka kovil', 'Ramakrishna hospital, Arugil'),
  (26, 'Erpinnar', null, 'Musunulla', 'Kondammal kovil', 'Karumatthampatti'),
  (27, 'Erra makkinaar', 'Yerrmasani', 'Maratla', 'Devara kovil', 'Chithanayakkanpalayam'),
  (28, 'Esoorar', null, 'Sendhutla', 'Perammal kovil; Aror + Devara kovil', 'A.Naagoor; karadikootam'),
  (29, 'Evinnar', null, 'Aavulapuli', 'Balarangamma', 'Iacchalapatti'),
  (30, 'Gandhappaar', 'Gandhamvru', 'Gindipaal, Cherukunulla', null, 'Perinayakkanvaladhu (Moolanoor)'),
  (31, 'Gundupillar', 'Guntupalli', 'Mannava, Marutla, Semandhala', 'lingammal kovil', 'Jangamanaayakkan paalayam'),
  (32, 'Inukullar', 'Inukula', 'Inakandi', 'Naarammal, Endammal kovil', 'Ramipalayam, Sevur'),
  (33, 'Ithar', null, 'Dhanabal', 'Devara kovil', 'Manjuvalli, Vedachandur'),
  (34, 'Jallor', 'Jalari', 'Pyindibal', 'Kondammal kovil', 'Petthinaayakkanoor'),
  (35, 'Janasatlaar', null, 'Padusoori', 'Peddhammal kovil', 'Pacchar palayam'),
  (36, 'Kaalasthriyaar', 'Kalahasthi', 'Ravipalla, Pamidipalla', 'Devara kovil', 'Ilakkarandhei, Arupukottei'),
  (37, 'Kaaliyar', 'Kalla', 'Pamidipalla, Thallri', 'Akkammal kovil', 'Sengaali Paalayam'),
  (38, 'Kaangallar', null, 'Miledi', 'Devara kovil', 'Veeriyampaalayam'),
  (39, 'Kaangallar', null, null, 'Devara kovil', 'Oornayakkan Valasu'),
  (40, 'Kaangallar', null, 'Myleti', 'Chithammal kovil', 'GKD nagar, Paapanaayakkanpaalayam'),
  (41, 'Kaangallar', null, null, 'Ellammal kovil', 'Ammapatti'),
  (42, 'Kaangallar', 'Kakarla', 'Miledi, Myleti, Mamilla', 'Sri Renukadevi Ellammal kovil', 'Peelamedu'),
  (43, 'Kaangallar', 'Kakarla', null, 'Perammal kovil', 'Periyanaayakkan Palayam'),
  (44, 'Kaangallar, Nelraar, Olraar', null, null, 'Endammal Rajammal Chithammal kovil', 'Kalapatti'),
  (45, 'Kadhirivaar', 'Kadiri', 'Sandapalli, Kollutla', null, 'Nallakavundan Paalayam (Kodumudi)'),
  (46, 'Keelaraar', 'Kilaru/Kilari', 'Vallutla, Pulipalla, Senoori', 'Devara kovil', 'Idikarei'),
  (47, 'Kendaar', 'Kenna/Kenneni/Kennina', 'Pamidipala, Eendharu maakkalla', 'Devara kovil', 'Chithanayakkanpalayam'),
  (48, 'Kenneraar', null, 'Pamidipalla, Sri Bala', 'Endammal Venugopaal Lakshmi Ammal', 'Kovei'),
  (49, 'Kenninnavar', 'Kennina', 'Pamidipalla, Gunabaal', 'Rangammal kovil', 'Mondipaalayam'),
  (50, 'Kenninnivaar', 'Kennina/Kenneni', 'Pamidipalla', 'Rangammal kovil', 'Naduvappatti (kovilpatti)'),
  (51, 'Kesaar', 'Kesani', 'Marutla, Pintpaal', 'Gangammal kovil', 'Ammapatti, Sanuppati'),
  (52, 'Kilaarar', 'Kilari', 'Vallutla, Kornipalla, Endhilla', 'Devara kovil; Kallazhagar kovil', 'Idikarei; Madurai'),
  (53, 'Kobattiyaar, Balakudiyaar', null, null, 'Ellammal Akkammal kovil', 'Govindapuram'),
  (54, 'Kobelaar', null, 'Gogunulla, Piyindipaal', 'Errammal kovil', 'Kallapalayam'),
  (55, 'Kodinnar', 'Kodi', 'Musunulla, Ipparali', 'Ruthrammal kovil', 'Ruthrayampaalayam'),
  (56, 'Kodunnar', 'Koduri', 'Inaganti, Sennamudi', 'Elammal kovil, Devara kovil', 'kalapatti'),
  (57, 'Kolraar', null, null, 'Thaayamman kovil', 'Paarapatti (Sivakasi)'),
  (58, 'Kolraar', 'Kolluru/Kolluri', 'Recherla, Chennamudi', 'Kondammal', 'Sembaarapatti (Vedachandoor)'),
  (59, 'Kondar', 'Konda', 'Eendamukula', 'Lakshmi Ammal lingammal kovil', 'Kondaar paalayam'),
  (60, 'Kongooraar', 'Kongara', 'Ullatla', 'Elammal kovil', 'Virukalapatti'),
  (61, 'Koorakaayalaar', 'Kuralla/Kuragayala', 'Maaratla', 'Devara kovil', 'Pennivaadi'),
  (62, 'Koppinar', 'Koppaku', 'Pamidipalla, Vipparla', 'Engalammal', 'Chinnakaliyamuthoor, Pazhani'),
  (63, 'Korandalaar', 'Koraganti', 'Pogunulla, Korujalli', 'Sri Renukadevi endammal kovil', 'Ondipudur'),
  (64, 'Korappatiyaar', 'Korrapati', 'Cherukuru, Dhasatla', 'Ellammal kovil', 'Ondipudhur, Kovei'),
  (65, 'Korappatiyaar', null, null, 'Veerammal kovil', 'Arungulam (Vilaathikulam)'),
  (66, 'korijalaar', null, null, 'Paadhaal Akkammal kovil', 'Andhiyoor'),
  (67, 'Korijalaar', 'Korijala', 'Pasupunulla', 'Chithammal kovil', 'Dhasarapatti (Thaarapuram)'),
  (68, 'Kothapillar', 'Kothapalli', 'Cherukunulla, Kasarakoori', 'Maadhammal kovil', 'Akkanaayakkan palayam'),
  (69, 'Kotta paadiyaar', 'Kotapati', 'Vallutla, Pogunulla, Kanooli', 'Endammal kovil', 'Thimma Naayakkanpalayam'),
  (70, 'Kover', 'Kovi', 'Gogunulla', null, 'Sikkal noothu'),
  (71, 'Kudhiyaar', null, 'Eesalla', 'Devara kovil', 'Kumaarapaalayam'),
  (72, 'Kudhiyaar', null, 'Erpulla', 'Venugopalasaami Nayurdu Rangammal kovil', 'Allappalayam'),
  (73, 'Kujchalaar', 'Kuchivaru', 'Poorandal', null, 'Ilavandhi Vadugapalayam'),
  (74, 'Kujeelupindiyaar', 'Kuchipudi', 'Pavilla, Pogunulla', 'Ellammal kovilo', 'Narikalpatti'),
  (75, 'Kunraar', 'Kuna', null, 'Devarakovil', 'Neikaarapatti'),
  (76, 'Langaar', 'Lanka', 'Mamilla, Chennamalla, Korapatla', 'Perammal kovil', null),
  (77, 'Lingatlaar', 'Lingutla', 'Yellutla, Perala, Acchandhala', 'lingammal Kondayammal kovil', 'Venkatapuram'),
  (78, 'Maarthaar', null, null, 'Devara kovil', 'Kallipalayam (Udumalai)'),
  (79, 'Maarthaar', 'Martha', 'Dosanulla', 'Errammal kovil', 'Appanayakkanpatti, Pudur'),
  (80, 'Makkinnar', 'Makkina', 'Dhanyala, Maratla', 'Perumal Sennammal kovil', 'Ketthanur'),
  (81, 'Makkinnar', 'Makkina/Makkena', null, 'Kondama thonamma kovil', 'Sappatipill'),
  (82, 'Mallinnaar', null, null, 'Lingammal kovil', 'Kalapatti'),
  (83, 'Mallinaar', null, null, 'Lingammal kovil', 'No.24 Veerapandi'),
  (84, 'Mallinnar', null, null, 'Lingammal kovil', 'Konapalayam'),
  (85, 'Mallinnar', null, null, 'Devara kovil', 'Ikkar palayam'),
  (86, 'Mallinnar', 'Mallina', 'Adhukoori', 'Lngammal kovil', 'Kallapalayam'),
  (87, 'Mallinnar', 'Mallina', 'Kancherla, Athikoori', 'Lingammal kovil', 'Peelamedu'),
  (88, 'Mallinnar', 'Mallina', null, 'ILngammal kovil', 'Vazhiyampalayam'),
  (89, 'Mandhapattiyaar', 'Mandapati', 'Marutla, Vipparla, Pulikorla', 'Perammal kovil', 'Peelamedu, S.N.R Kaloori saalei'),
  (90, 'Manjillar', 'Manchineella', 'Komaravolu, Valootla', 'Akkammal kovil', 'Sennavanayakkanpalayam'),
  (91, 'Manner', 'Manne', 'Gogunulla, Ayodhya, Karapatla', 'Lakshmi ammal koil', 'A.Nagoor'),
  (92, 'Manooraar', 'Mannuri', 'Tatipala, Sri bala', 'Endammal kovil', 'Ramiyapalayam'),
  (93, 'Marivaadiyaar', 'Marivada', 'Enulla, Noongalla', 'Govindhammal kovil', 'Pongaloor'),
  (94, 'Matulooraar', 'Matluri', 'Chedimatla, Rayakalli', 'Devara kovil', 'Nalla kavundanpaalayam, Kodumudi'),
  (95, 'Medhala metlaar', 'Medarametla', 'Tammaluri, Ayodhya', 'Alamelu mangammal kovil', 'Sennava Nayakkanpalayam'),
  (96, 'Megalaar', null, 'Pongu noola', 'Devara kovil', 'Nagarkalandei'),
  (97, 'Megalaar', 'Mekala', 'Nugunulla, Pongu noola', 'Endammal kovil', 'Mondipalayam'),
  (98, 'Modhaka pallivaar', 'Modapalli', 'Talluru', 'Azhagammal kovil', 'Nadiyaneri (Vilaathikulam)'),
  (99, 'Mogooraar', null, 'Inakandi', 'Devara kovil', 'Chithanayakkanpalayam'),
  (100, 'Molraar', 'Molakala', 'Vallutla', 'Nagammal kovil', 'Karungalpati, Aandipatti kottei'),
  (101, 'Munningi', 'Munnamgi', 'Vallutla, Vullatla, Vallavetu', null, null),
  (102, 'Musunnar', 'Musunuru', 'Ethamukkala, Dosappadi', 'Srinivasaperumal koil', 'Nadupatti'),
  (103, 'Muthinnar', null, null, 'Lingammal kovil, Elammal kovil, Devara kovil', 'Kalapatti'),
  (104, 'Muthinnar', 'Muthineni/Muthini', 'Vallutla, Meda, Erranoola', 'Lingammal kovil', 'Aavarampalayam'),
  (105, 'Naadhallar', 'Nadella', 'Desatla, Chandrolla, Sennamudi', 'Chithammal kovil', 'R.Veloor'),
  (106, 'Naangillaar', 'Nagalla', 'Kancherla, Kanakavall', 'Chithammal nayudu, Polammal kovil', 'Thandukaranpalayam, Sevoor'),
  (107, 'Naatangallaar', 'Nathani', 'Inaganti', 'Devara kovil', 'Elavanoor (Aravei); Nimmalaar, Akkanaayakkan palayam'),
  (108, 'Naginnar', 'Nagineni', 'Garalakanta, Garikanolla', 'Maadhammal Gengammal kovil', 'Sanuppapatti'),
  (109, 'Nambooraar', 'Namburi', 'Aduri, Mogilirekula', 'Rayar Kaatupillar kovil', 'Periyanaayakkanpalayam'),
  (110, 'Namboorar', null, null, 'Rangammal kovil', 'Maniyakaranpalayam'),
  (111, 'Namboorar', null, null, 'Rangammal kovil', 'Aavarampalayam'),
  (112, 'Namboorar', null, 'Edutla', 'Rangammal kovil', 'Peelamedu'),
  (113, 'Namboorar, Thookinnar', null, 'Beenari', 'Rangammal kovil', 'Paapanaayakkanpalaya'),
  (114, 'Namboorar, Edulathukkunaar', null, 'Beemaari', 'Rangammaal kovil', 'Madukattipalayam'),
  (115, 'Namboorar, Thookinnar', null, null, 'Rangammal kovil', 'Puloiyampatti'),
  (116, 'Narlaar', 'Narla', 'Pogunulla, Vipparla', 'Sri Renukadevi Gangammal kovil', 'Seethampatti engira venkita puram, Dindigul maavattam'),
  (117, 'Neer kondaar', null, 'Pogunulla', 'Mangammal kovil', 'pulimarathuppalayam'),
  (118, 'Neerkondaar', null, null, 'Devara kovil', 'Andhiyoor'),
  (119, 'Neerkondaar', null, null, 'Devara kovil', 'Krishnapuram, OIttansathiram'),
  (120, 'Neerkondaar', null, null, 'Devara kovil', 'Chinnavanaayakkanoor (Aravei)'),
  (121, 'Neerkondaar', null, null, 'Devara kovil', 'Therapaadi (Karoor vattam)'),
  (122, 'Neerkondaar', null, null, 'Gengammal kovil', 'Annappalayam (Karoor)'),
  (123, 'Neerkondaar', 'Neerukonda', 'Pogunulla, Etipaal', 'Endammal kovil', 'Peelamedu'),
  (124, 'Neerkondaar, Thandaar', null, 'Pulikorla', 'Endammal kovil', 'S.N.R college, Kovei'),
  (125, 'Nelraar', 'Nelluri', 'Palapudi', 'Devara kovil', 'Kalapatti'),
  (126, 'Olapallar', null, 'Valluri', 'mangammal kovil', 'naayakkanoor'),
  (127, 'Oleeraar', null, 'Vallur', 'Akkammal kovil', 'Vasavanayakkanpatti (Pasaveipill)'),
  (128, 'Oolapallar', null, 'Vallur', 'Gengammal kovil', 'Velapatti chanthriram'),
  (129, 'Ottadindiyaar', null, 'Amaraavathi', null, 'Veerlappatti'),
  (130, 'Paalkudiyaar', 'Palakurthi', 'Pongu noola', 'Akkammal Venugopalsamy kovil', 'Ondipudur')
on conflict (id) do nothing;
