-- Seed the kulams table (221 entries, with coordinates where geocoded).
-- Paste into the Supabase SQL editor AFTER running schema.sql. Safe to re-run.

insert into public.kulams (id, surname, house, gothram, kuladeivam, place, lat, lng) values
  (1, 'Aarer', 'Aare', 'Yenulla, Yelpunulla', 'Devara kovil', 'Erichinapati (Pallapati)', 10.95, 77.2),
  (2, 'Aarikatlaar', 'Arikatla', 'Palulla, Cherukunulla, Selukoori', 'Devara kovil', 'Chinnametupaalayam', null, null),
  (3, 'Aarikattalaar', null, null, 'Guruvammal Gurusaami Konammal kovil', 'Ammapatti', 10.82483, 78.09341),
  (4, 'Aavula maarthar', 'Avula', 'Ponnuri, Pogunulla', 'Angaala Parameshwari kovil', 'Palladam', 10.9708, 77.2817),
  (5, 'Adugullar', null, null, 'Aevara kovil', 'Ayyampati, Aravakurichi', null, null),
  (6, 'Angalakuricher', 'Angalakuduru', 'Maadhalla', 'Mangammal Beddhakka kovil', 'Kaanur, Pudur', 11.2696882, 77.171898),
  (7, 'Anumoloorar', 'Anumlu', 'Eesalla', 'Konammal kovil', 'Madoorampatti', null, null),
  (8, 'Beemannar', 'Bheemananeni', 'Marutla, Pamidipalla', 'Naagammal kovil', 'Thaarapuram, Uppar Arugil', null, null),
  (9, 'Chandragiriyaar', 'Chandragiri', 'Pognulla, Pongunoola', 'Lakshmi ammal kovil', 'Aavarampaalayam', 11.029, 76.987),
  (10, 'Chennai', 'Chennupati', 'Pogunulla, Pasupu neela', 'Konammal kovil', 'Idikarei', null, null),
  (11, 'Dharmapuriyaar', 'dharmapuram', 'Vipparla, Punugoti Valoottal', 'Ruthrammal Kovil', 'Viyampaalayam', null, null),
  (12, 'Dhivyaar, Pejavaadiyaar', null, null, 'Naagammal kovil', 'Thaarapuram, Uppar Arugil', null, null),
  (13, 'Edugullar', null, null, 'Ellammal kovil', 'Kongappatti, Attanchathiram', null, null),
  (14, 'Edugullar', null, null, 'Devara kovil', 'Kothappaalayam (Aravei)', null, null),
  (15, 'Edugullar', null, null, 'Devara kovil', 'Poolakkampatti', null, null),
  (16, 'Eendalaar', null, 'Noonavalli', 'Devara kovil', 'Ammapatti', 10.82483, 78.09341),
  (17, 'Eeramanjar', 'Veeramachneni', 'Mangapuri', 'Matthamma Govindammal kovil', 'Devanampalayam', 10.7688275, 77.076331),
  (18, 'Eelamaar', null, null, null, 'Naranaapuram', 10.7018601, 77.382292),
  (19, 'Eminnar', 'Yemineni', 'Janakanulla', 'Sri Renuka Ellammal kovil', 'Dalamarathupati, Karor vattam', null, null),
  (20, 'Endapillaar', 'Yendapalli', 'Kundhitla', 'Endammal Mathraalammal kovil', 'Uppilipaalayam', 11, 77),
  (21, 'Enukundaar', null, null, 'Devara kovil', 'Poolankinaru (udumalai)', 10.5862, 77.2497),
  (22, 'Enukundaar', null, 'Inakandi', 'Endammal kovil', 'Komangalam', null, null),
  (23, 'Enukundaar, Pocchinnar', null, null, 'Poodhaatiyaar kovil', 'Komangalam', null, null),
  (24, 'Eravandaar', null, 'Thalluri', 'Endammal China Endammal Kasthurinayurdu kovil', 'Pongaloor', null, null),
  (25, 'Erivinnar', null, 'Thalluri', 'Beddhakka kovil', 'Ramakrishna hospital, Arugil', 11.0207084, 76.972413),
  (26, 'Erpinnar', null, 'Musunulla', 'Kondammal kovil', 'Karumatthampatti', null, null),
  (27, 'Erra makkinaar', 'Yerrmasani', 'Maratla', 'Devara kovil', 'Chithanayakkanpalayam', null, null),
  (28, 'Esoorar', null, 'Sendhutla', 'Perammal kovil; Aror + Devara kovil', 'A.Naagoor; karadikootam', null, null),
  (29, 'Evinnar', null, 'Aavulapuli', 'Balarangamma', 'Iacchalapatti', null, null),
  (30, 'Gandhappaar', 'Gandhamvru', 'Gindipaal, Cherukunulla', null, 'Perinayakkanvaladhu (Moolanoor)', null, null),
  (31, 'Gundupillar', 'Guntupalli', 'Mannava, Marutla, Semandhala', 'lingammal kovil', 'Jangamanaayakkan paalayam', null, null),
  (32, 'Inukullar', 'Inukula', 'Inakandi', 'Naarammal, Endammal kovil', 'Ramipalayam, Sevur', null, null),
  (33, 'Ithar', null, 'Dhanabal', 'Devara kovil', 'Manjuvalli, Vedachandur', null, null),
  (34, 'Jallor', 'Jalari', 'Pyindibal', 'Kondammal kovil', 'Petthinaayakkanoor', null, null),
  (35, 'Janasatlaar', null, 'Padusoori', 'Peddhammal kovil', 'Pacchar palayam', null, null),
  (36, 'Kaalasthriyaar', 'Kalahasthi', 'Ravipalla, Pamidipalla', 'Devara kovil', 'Ilakkarandhei, Arupukottei', null, null),
  (37, 'Kaaliyar', 'Kalla', 'Pamidipalla, Thallri', 'Akkammal kovil', 'Sengaali Paalayam', null, null),
  (38, 'Kaangallar', null, 'Miledi', 'Devara kovil', 'Veeriyampaalayam', null, null),
  (39, 'Kaangallar', null, null, 'Devara kovil', 'Oornayakkan Valasu', null, null),
  (40, 'Kaangallar', null, 'Myleti', 'Chithammal kovil', 'GKD nagar, Paapanaayakkanpaalayam', null, null),
  (41, 'Kaangallar', null, null, 'Ellammal kovil', 'Ammapatti', 10.82483, 78.09341),
  (42, 'Kaangallar', 'Kakarla', 'Miledi, Myleti, Mamilla', 'Sri Renukadevi Ellammal kovil', 'Peelamedu', null, null),
  (43, 'Kaangallar', 'Kakarla', null, 'Perammal kovil', 'Periyanaayakkan Palayam', null, null),
  (44, 'Kaangallar, Nelraar, Olraar', null, null, 'Endammal Rajammal Chithammal kovil', 'Kalapatti', 11.075, 77.03),
  (45, 'Kadhirivaar', 'Kadiri', 'Sandapalli, Kollutla', null, 'Nallakavundan Paalayam (Kodumudi)', 11.078, 77.883),
  (46, 'Keelaraar', 'Kilaru/Kilari', 'Vallutla, Pulipalla, Senoori', 'Devara kovil', 'Idikarei', null, null),
  (47, 'Kendaar', 'Kenna/Kenneni/Kennina', 'Pamidipala, Eendharu maakkalla', 'Devara kovil', 'Chithanayakkanpalayam', null, null),
  (48, 'Kenneraar', null, 'Pamidipalla, Sri Bala', 'Endammal Venugopaal Lakshmi Ammal', 'Kovei', null, null),
  (49, 'Kenninnavar', 'Kennina', 'Pamidipalla, Gunabaal', 'Rangammal kovil', 'Mondipaalayam', 11.2596488, 77.1728008),
  (50, 'Kenninnivaar', 'Kennina/Kenneni', 'Pamidipalla', 'Rangammal kovil', 'Naduvappatti (kovilpatti)', 9.17559, 77.8687),
  (51, 'Kesaar', 'Kesani', 'Marutla, Pintpaal', 'Gangammal kovil', 'Ammapatti, Sanuppati', 10.82483, 78.09341),
  (52, 'Kilaarar', 'Kilari', 'Vallutla, Kornipalla, Endhilla', 'Devara kovil; Kallazhagar kovil', 'Idikarei; Madurai', null, null),
  (53, 'Kobattiyaar, Balakudiyaar', null, null, 'Ellammal Akkammal kovil', 'Govindapuram', null, null),
  (54, 'Kobelaar', null, 'Gogunulla, Piyindipaal', 'Errammal kovil', 'Kallapalayam', 10.9524, 77.0806),
  (55, 'Kodinnar', 'Kodi', 'Musunulla, Ipparali', 'Ruthrammal kovil', 'Ruthrayampaalayam', null, null),
  (56, 'Kodunnar', 'Koduri', 'Inaganti, Sennamudi', 'Elammal kovil, Devara kovil', 'kalapatti', 11.075, 77.03),
  (57, 'Kolraar', null, null, 'Thaayamman kovil', 'Paarapatti (Sivakasi)', 10.8061809, 78.0015135),
  (58, 'Kolraar', 'Kolluru/Kolluri', 'Recherla, Chennamudi', 'Kondammal', 'Sembaarapatti (Vedachandoor)', 10.53, 77.95),
  (59, 'Kondar', 'Konda', 'Eendamukula', 'Lakshmi Ammal lingammal kovil', 'Kondaar paalayam', null, null),
  (60, 'Kongooraar', 'Kongara', 'Ullatla', 'Elammal kovil', 'Virukalapatti', null, null),
  (61, 'Koorakaayalaar', 'Kuralla/Kuragayala', 'Maaratla', 'Devara kovil', 'Pennivaadi', null, null),
  (62, 'Koppinar', 'Koppaku', 'Pamidipalla, Vipparla', 'Engalammal', 'Chinnakaliyamuthoor, Pazhani', null, null),
  (63, 'Korandalaar', 'Koraganti', 'Pogunulla, Korujalli', 'Sri Renukadevi endammal kovil', 'Ondipudur', 10.995, 77.03),
  (64, 'Korappatiyaar', 'Korrapati', 'Cherukuru, Dhasatla', 'Ellammal kovil', 'Ondipudhur, Kovei', null, null),
  (65, 'Korappatiyaar', null, null, 'Veerammal kovil', 'Arungulam (Vilaathikulam)', 9.128, 78.157),
  (66, 'korijalaar', null, null, 'Paadhaal Akkammal kovil', 'Andhiyoor', null, null),
  (67, 'Korijalaar', 'Korijala', 'Pasupunulla', 'Chithammal kovil', 'Dhasarapatti (Thaarapuram)', 10.7297, 77.532),
  (68, 'Kothapillar', 'Kothapalli', 'Cherukunulla, Kasarakoori', 'Maadhammal kovil', 'Akkanaayakkan palayam', null, null),
  (69, 'Kotta paadiyaar', 'Kotapati', 'Vallutla, Pogunulla, Kanooli', 'Endammal kovil', 'Thimma Naayakkanpalayam', null, null),
  (70, 'Kover', 'Kovi', 'Gogunulla', null, 'Sikkal noothu', null, null),
  (71, 'Kudhiyaar', null, 'Eesalla', 'Devara kovil', 'Kumaarapaalayam', 11.3882525, 77.7778376),
  (72, 'Kudhiyaar', null, 'Erpulla', 'Venugopalasaami Nayurdu Rangammal kovil', 'Allappalayam', null, null),
  (73, 'Kujchalaar', 'Kuchivaru', 'Poorandal', null, 'Ilavandhi Vadugapalayam', null, null),
  (74, 'Kujeelupindiyaar', 'Kuchipudi', 'Pavilla, Pogunulla', 'Ellammal kovilo', 'Narikalpatti', null, null),
  (75, 'Kunraar', 'Kuna', null, 'Devarakovil', 'Neikaarapatti', null, null),
  (76, 'Langaar', 'Lanka', 'Mamilla, Chennamalla, Korapatla', 'Perammal kovil', null, null, null),
  (77, 'Lingatlaar', 'Lingutla', 'Yellutla, Perala, Acchandhala', 'lingammal Kondayammal kovil', 'Venkatapuram', 10.8355833, 78.1273816),
  (78, 'Maarthaar', null, null, 'Devara kovil', 'Kallipalayam (Udumalai)', 11.1160301, 77.0638372),
  (79, 'Maarthaar', 'Martha', 'Dosanulla', 'Errammal kovil', 'Appanayakkanpatti, Pudur', null, null),
  (80, 'Makkinnar', 'Makkina', 'Dhanyala, Maratla', 'Perumal Sennammal kovil', 'Ketthanur', null, null),
  (81, 'Makkinnar', 'Makkina/Makkena', null, 'Kondama thonamma kovil', 'Sappatipill', null, null),
  (82, 'Mallinnaar', null, null, 'Lingammal kovil', 'Kalapatti', 11.075, 77.03),
  (83, 'Mallinaar', null, null, 'Lingammal kovil', 'No.24 Veerapandi', null, null),
  (84, 'Mallinnar', null, null, 'Lingammal kovil', 'Konapalayam', null, null),
  (85, 'Mallinnar', null, null, 'Devara kovil', 'Ikkar palayam', null, null),
  (86, 'Mallinnar', 'Mallina', 'Adhukoori', 'Lngammal kovil', 'Kallapalayam', 10.9524, 77.0806),
  (87, 'Mallinnar', 'Mallina', 'Kancherla, Athikoori', 'Lingammal kovil', 'Peelamedu', null, null),
  (88, 'Mallinnar', 'Mallina', null, 'ILngammal kovil', 'Vazhiyampalayam', null, null),
  (89, 'Mandhapattiyaar', 'Mandapati', 'Marutla, Vipparla, Pulikorla', 'Perammal kovil', 'Peelamedu, S.N.R Kaloori saalei', null, null),
  (90, 'Manjillar', 'Manchineella', 'Komaravolu, Valootla', 'Akkammal kovil', 'Sennavanayakkanpalayam', null, null),
  (91, 'Manner', 'Manne', 'Gogunulla, Ayodhya, Karapatla', 'Lakshmi ammal koil', 'A.Nagoor', null, null),
  (92, 'Manooraar', 'Mannuri', 'Tatipala, Sri bala', 'Endammal kovil', 'Ramiyapalayam', null, null),
  (93, 'Marivaadiyaar', 'Marivada', 'Enulla, Noongalla', 'Govindhammal kovil', 'Pongaloor', null, null),
  (94, 'Matulooraar', 'Matluri', 'Chedimatla, Rayakalli', 'Devara kovil', 'Nalla kavundanpaalayam, Kodumudi', null, null),
  (95, 'Medhala metlaar', 'Medarametla', 'Tammaluri, Ayodhya', 'Alamelu mangammal kovil', 'Sennava Nayakkanpalayam', null, null),
  (96, 'Megalaar', null, 'Pongu noola', 'Devara kovil', 'Nagarkalandei', null, null),
  (97, 'Megalaar', 'Mekala', 'Nugunulla, Pongu noola', 'Endammal kovil', 'Mondipalayam', 11.2596488, 77.1728008),
  (98, 'Modhaka pallivaar', 'Modapalli', 'Talluru', 'Azhagammal kovil', 'Nadiyaneri (Vilaathikulam)', 9.128, 78.157),
  (99, 'Mogooraar', null, 'Inakandi', 'Devara kovil', 'Chithanayakkanpalayam', null, null),
  (100, 'Molraar', 'Molakala', 'Vallutla', 'Nagammal kovil', 'Karungalpati, Aandipatti kottei', null, null),
  (101, 'Munningi', 'Munnamgi', 'Vallutla, Vullatla, Vallavetu', null, null, null, null),
  (102, 'Musunnar', 'Musunuru', 'Ethamukkala, Dosappadi', 'Srinivasaperumal koil', 'Nadupatti', 11.2676132, 78.1991794),
  (103, 'Muthinnar', null, null, 'Lingammal kovil, Elammal kovil, Devara kovil', 'Kalapatti', 11.075, 77.03),
  (104, 'Muthinnar', 'Muthineni/Muthini', 'Vallutla, Meda, Erranoola', 'Lingammal kovil', 'Aavarampalayam', 11.029, 76.987),
  (105, 'Naadhallar', 'Nadella', 'Desatla, Chandrolla, Sennamudi', 'Chithammal kovil', 'R.Veloor', null, null),
  (106, 'Naangillaar', 'Nagalla', 'Kancherla, Kanakavall', 'Chithammal nayudu, Polammal kovil', 'Thandukaranpalayam, Sevoor', 11.2740593, 77.1859556),
  (107, 'Naatangallaar', 'Nathani', 'Inaganti', 'Devara kovil', 'Elavanoor (Aravei); Nimmalaar, Akkanaayakkan palayam', null, null),
  (108, 'Naginnar', 'Nagineni', 'Garalakanta, Garikanolla', 'Maadhammal Gengammal kovil', 'Sanuppapatti', null, null),
  (109, 'Nambooraar', 'Namburi', 'Aduri, Mogilirekula', 'Rayar Kaatupillar kovil', 'Periyanaayakkanpalayam', null, null),
  (110, 'Namboorar', null, null, 'Rangammal kovil', 'Maniyakaranpalayam', 11.0481388, 76.9749196),
  (111, 'Namboorar', null, null, 'Rangammal kovil', 'Aavarampalayam', 11.029, 76.987),
  (112, 'Namboorar', null, 'Edutla', 'Rangammal kovil', 'Peelamedu', null, null),
  (113, 'Namboorar, Thookinnar', null, 'Beenari', 'Rangammal kovil', 'Paapanaayakkanpalaya', null, null),
  (114, 'Namboorar, Edulathukkunaar', null, 'Beemaari', 'Rangammaal kovil', 'Madukattipalayam', null, null),
  (115, 'Namboorar, Thookinnar', null, null, 'Rangammal kovil', 'Puloiyampatti', null, null),
  (116, 'Narlaar', 'Narla', 'Pogunulla, Vipparla', 'Sri Renukadevi Gangammal kovil', 'Seethampatti engira venkita puram, Dindigul maavattam', null, null),
  (117, 'Neer kondaar', null, 'Pogunulla', 'Mangammal kovil', 'pulimarathuppalayam', null, null),
  (118, 'Neerkondaar', null, null, 'Devara kovil', 'Andhiyoor', null, null),
  (119, 'Neerkondaar', null, null, 'Devara kovil', 'Krishnapuram, OIttansathiram', 10.2388661, 77.8766835),
  (120, 'Neerkondaar', null, null, 'Devara kovil', 'Chinnavanaayakkanoor (Aravei)', null, null),
  (121, 'Neerkondaar', null, null, 'Devara kovil', 'Therapaadi (Karoor vattam)', 10.81025, 77.96497),
  (122, 'Neerkondaar', null, null, 'Gengammal kovil', 'Annappalayam (Karoor)', 10.96, 78.08),
  (123, 'Neerkondaar', 'Neerukonda', 'Pogunulla, Etipaal', 'Endammal kovil', 'Peelamedu', null, null),
  (124, 'Neerkondaar, Thandaar', null, 'Pulikorla', 'Endammal kovil', 'S.N.R college, Kovei', null, null),
  (125, 'Nelraar', 'Nelluri', 'Palapudi', 'Devara kovil', 'Kalapatti', 11.075, 77.03),
  (126, 'Olapallar', null, 'Valluri', 'mangammal kovil', 'naayakkanoor', null, null),
  (127, 'Oleeraar', null, 'Vallur', 'Akkammal kovil', 'Vasavanayakkanpatti (Pasaveipill)', null, null),
  (128, 'Oolapallar', null, 'Vallur', 'Gengammal kovil', 'Velapatti chanthriram', null, null),
  (129, 'Ottadindiyaar', null, 'Amaraavathi', null, 'Veerlappatti', null, null),
  (130, 'Paalkudiyaar', 'Palakurthi', 'Pongu noola', 'Akkammal Venugopalsamy kovil', 'Ondipudur', 10.995, 77.03),
  (131, 'Paalkudiyaar', 'Palakurthi', 'Dhaniyakula, Pongu noola', 'Akkammal Nagammal kovil', 'Ondipudur, Govindapuram', 10.995, 77.03),
  (132, 'Pacchalkuriyaar', 'Bachalakura', 'Vallutla, Marutla, Thoopaali', null, 'Kaalapatti', 11.075, 77.03),
  (133, 'Pachar', 'Pacha', 'Pamidipalla, Tatipalla, Paaledi', 'Akkammal kovil', 'Matthi nayakkan palayam', null, null),
  (134, 'Pachar', 'Pacha', 'Kundhatla', 'Akkammal kovil', 'Pottiyampalayam', null, null),
  (135, 'Pahaar', null, 'Kundhatla', 'Rangammal kovil', 'Guruvappa naayakkanoor', null, null),
  (136, 'Pahaar', 'Mkullu', 'Kundhatla', 'Thirupathi nayudu endammal kovil', 'Rajapalayam, chinnakalaiyamuthoor', null, null),
  (137, 'Pairpindiyaar', null, 'Kandhumadi', 'Mangalagiri ammal kovil', 'Anuppapatti', null, null),
  (138, 'Pandiyaar', 'Bandi', 'Vallutla, Marutla, Thaaloori', 'Chithammal Nayudu, Polammal kovil', 'Thandukaranpalayam, Sevoor', 11.2740593, 77.1859556),
  (139, 'Pangaar', 'Panga', 'Pamidipalla, Simakurthi, Sri bala', 'Mangammal, Venugopalsaamy nayudu kondammal kovil', 'Vellamadei', null, null),
  (140, 'Pangullar', 'Panguluri', 'Kundurthi, Pongu noola', 'Devara kovil', 'Therapaadi', 10.81025, 77.96497),
  (141, 'Parimaar', 'Parimi', 'Vallutla, Vipparla, Sirumulla', 'Gangammal kovil', 'Vandara chinnappatti, Gandipatti kottei', null, null),
  (142, 'Pathi pattiyar', 'Pathipati', 'Vipparla, Vemunulla, Namagiri', 'Endammal kovil', 'Pongaloor', null, null),
  (143, 'Pathipatiyaar', 'Pathipati', 'Vemunulla, Vippattula, Korapati', 'Chithammal kovil', 'Dhasarapatti', null, null),
  (144, 'Pattaar', 'Batta', 'Tanguturu', 'Devara kovil', 'Vallappampatti', null, null),
  (145, 'Pedda megalaar', null, null, 'Devara kovil', 'Aandipatti (Paramathi Veloor)', 10.9828701, 77.9654662),
  (146, 'Pellamma', 'Bellam', 'Paleti, Paaledi', 'Devara kovil', 'Eppodhum venraan', null, null),
  (147, 'Pepallar', 'Pepalla', 'Inakandi', 'Ragammal kovil', 'Poolanginar', null, null),
  (148, 'Perugaar', 'Perugu', 'Daasaraar', 'Endammal kovil', 'Ramiyampalayam', null, null),
  (149, 'Perugaar', 'Perugu', null, 'Devara kovil', 'Pethoindipilla', null, null),
  (150, 'Pidikattar', 'Pidikita', 'Korrapala, Inakandi', 'Chithammal kovil', 'Ramiyampalayam', null, null),
  (151, 'Pikkusennar', null, null, 'Devara kovil', 'Chinnamettu palayam', null, null),
  (152, 'Pikkusennar', null, null, 'Naanammal kovil', 'Chandrapuram', 10.89953, 77.183846),
  (153, 'Pikkusennar', 'Bikkasani', 'Jutlunulla, Sootoor', 'Devara kovil', 'China mettu palayam', null, null),
  (154, 'Pikkusennar', 'Bikkasani', null, 'Devara kovil', 'Appanayakkanpatti', null, null),
  (155, 'Pindhukondaar', null, null, 'Kommakka kovil', 'Velliyampalayam', 11.2833641, 77.8268317),
  (156, 'Pirudhukondaar', 'Birudukonda', 'Veiloola', 'Bommakka kovil', 'Kanuvakkarei', null, null),
  (157, 'Podhaar', 'Poda', 'Ullatla', 'Venkitusaami nayudu, endammal kovil', 'Sikkal noothu', null, null),
  (158, 'Polinar', 'Polina', 'Mandepudi, Mandipidi', null, null, null, null),
  (159, 'Pollinnar', 'Bollina', 'Talluru, Pallanti, Thaatipal', 'Annammal annava nayudu akkammal kovil', 'Lakshminayakkanpalayam', null, null),
  (160, 'Pommamampatti, Sigarpattiyaar', null, null, 'Endammal kovil', 'Poolanginar', null, null),
  (161, 'Pomminnar', 'Bommineni', 'Talluri', 'Mangammal kovil', 'Poruloor, Pazhani', null, null),
  (162, 'Poodhandiyaar', 'Pudanti', 'Chennamalla', 'Paradesi Rangammal, Konda Perammal kovil', 'Devanampalayam', 10.7688275, 77.076331),
  (163, 'Poodhantlaar', 'Poodotha', 'Pannulu, Serukoori', 'Kendaperammal Balarangammal kovil', 'Devanampaalayam', 10.7688275, 77.076331),
  (164, 'Popuraar', 'Popuri', 'Ullatla', 'Lakshmi ammal kovil', 'Thottampatti', 10.9798905, 77.7869797),
  (165, 'Pothillar', 'Podili', 'Vedanulla, Sri bala', 'Lakshmi kovil', 'Viyampalayam', null, null),
  (166, 'Potla gundaar', 'Botlagunta', 'Sri bala', 'Ellammal kovil', 'Ellappa nayakkanoor', null, null),
  (167, 'Puliyaar', 'Puli', 'Sandrolla, Eetha mokkala', 'Dhavathi amman kovil', 'Pazhani akkarapatti', null, null),
  (168, 'Purrar', 'Puri', 'Sannapuri, Maaratla', 'Devara kovil', 'Purra nayakkanoor (Koomboor, Vedachandoor)', null, null),
  (169, 'Puttar', null, null, 'Devara kovil', 'Chandirapatti (Kovilpatti)', 9.17559, 77.8687),
  (170, 'Puttar', 'Putta', 'Inakanti, Dharanipala, Inakandi', 'Nagammal kovil', 'Nettipatti', null, null),
  (171, 'Raaver', 'Ravuri', 'Guntur, Chennamalla, Pamidipalla', 'Errammal kovil', 'Devarajapattanam (Kundadam), Tharapuram', 10.74, 77.55),
  (172, 'Raayaar', null, 'Muppalla, Vallutla', 'Errammal kovil', 'Karappaadi', null, null),
  (173, 'Raayaar', null, null, 'Devara kovil', 'Kalaiya muthoor', null, null),
  (174, 'Raayaar', null, 'Kunugu noola', 'Errammal kovil', 'R.veloor', null, null),
  (175, 'Raja kondalaar', null, 'Pepalla', 'Mathammal Govindhammal kovil', 'Panniimadei', null, null),
  (176, 'Raja kondalaar', null, null, 'Devara kovil', 'Athipaalayam', 11.1291418, 76.9807251),
  (177, 'Raja kondalaar', 'Rasakondala', 'Pepalla', 'Mathammal Govindhammal kovil', 'Pannimadei', null, null),
  (178, 'Ramaar', 'Rama', 'Kandanulla, Pasupu noola', 'Akkammal kovil', 'Veeriyampaalayam', null, null),
  (179, 'Rathnaalaar', 'Ratnala', 'Srilakshmi, Erpell', 'Naanammal kovil', 'Nagamanaayakkan palayam, Pattanam', null, null),
  (180, '(Common) Renuka Devi', null, null, 'Renuka Devi kovil', 'Jothipuram', 11.1643267, 76.9489397),
  (181, 'Saakinnar', 'Sakineni', 'Vipparla, Ipparali', 'Endammal kovil', 'Varakuttapalayam', null, null),
  (182, 'Sakthi reddyar', null, 'Ullamala', 'Lakshmi ammal kovil', null, null, null),
  (183, 'Sallar', 'Sallapaneni', 'Recherla, Aranoori', 'Gengammal kovil', 'Murungappatti', null, null),
  (184, 'Sallkundaar', 'Sallagundla', 'Parishpalla', 'Devara kovil', 'Guruvappa Naayakkanoor, Naarapatti', null, null),
  (185, 'Sammebaar', 'Sammeta', 'Vallutla', 'Devi kovil', 'Lakshmipuram', 10.0801375, 77.5193964),
  (186, 'Sappatiyaar', 'Sappidi', 'Kancherla, Pulikorla', 'Lingammal kovil', 'Vaazhavaadi', 10.5475749, 77.1831996),
  (187, 'Sappitiyaar', 'Kudipayinda', 'Paidipala, Paindibal', 'Ayilammal kovil', 'China Vaazhapaadi', null, null),
  (188, 'Sappitiyaar', 'Sappidi', 'Puligorla, Payindibal', 'Thaathan kovil', 'Kavundanpaalayam', null, null),
  (189, 'Saripinnar', 'Sariputi', 'Avapuru, Aavulpuli', 'Lakshmi Ammal Kovil', 'Aavarampalayam', 11.029, 76.987),
  (190, 'Seekaar', 'Seku', 'Pongu noola', 'Akkammal kovil', 'Valiyapalayam', null, null),
  (191, 'Seemattakaangallar', null, null, 'Akkammal kovil', 'Poolvaadi, Rangasamuthiram', null, null),
  (192, 'Seethaar', null, 'Adhuku noola', 'Akkammal kovil', 'Veloor', null, null),
  (193, 'Semaar', null, 'Sirumulla', 'Guruvammal / Devara kovil', 'Pongaloor; Manjekavundan Pudhoor', null, null),
  (194, 'Sennar', null, 'Pasupunulla', 'Thathan koil, Konammal kovil', 'Kavundanpaalayam, Modakkupati', null, null),
  (195, 'Sennar, Namboraar, Thookinaar', null, null, 'Rayar kaatupillar kovil', 'Periyanayakkanpalayam', null, null),
  (196, 'Serukkooraar', 'Cherukuri', 'Marutla, Ullatla, Maaramala', 'Devara kovil', 'Kundavalasu; Narasingaapuram, Aravakkurichi', null, null),
  (197, 'Sigarpattiyar', 'Sigarapati', 'Kanoor', 'Rangammal kovil', 'Moolakkurumba paalayam', null, null),
  (198, 'Sigarpattiyar', 'Sigarapati/Chigurupati', 'Kanumanulla, Karumpoori', 'Sooramal kovil', 'Sallaarapalayam', null, null),
  (199, 'Sivattakaangallar', null, null, 'Akkammal kovil', 'Adivalli', null, null),
  (200, 'Sooriya kondalaar', 'Suryakondala', null, 'Kondammal kovil', 'Ravanavapuram', null, null),
  (201, 'Sovinnar', null, 'Ullatla', 'Rangammal kovil', 'Manjuvalli', null, null),
  (202, 'Sungarar', 'Sunkara', 'Marutla, Vipparla', 'Unnal kovil', 'Thalijallipatti', null, null),
  (203, 'Sunjaar', null, 'Maaratla', 'Endammal kovil', 'Karadivaavi', 10.9668139, 77.1931099),
  (204, 'Thaalraar', 'Talluri', null, 'Poodhaatiyaar kovil', 'Komangalam', null, null),
  (205, 'Thaavullar', 'Davuluri', 'Cherukunulla, Serukkoori', 'Rangammal lakshmiyammal kovil', 'Sikkalnoothu', null, null),
  (206, 'Thakkupattiyar', 'Daggubati', 'Srikanta, Eendham kola', 'Rangammal lakshmiyammal kovil', 'Sikkalnoothu', null, null),
  (207, 'Thamminnar', 'Thammina/Thammineni', 'Mallepuvvula, Prepala, Tritaloka, Thinoolla', 'Chithammal nayudu, Polammal kovil', 'Thandukaranpalayam, Sevoor', 11.2740593, 77.1859556),
  (208, 'Thandaar', 'Thandra', 'Cherukupalla, Pulikorlu', null, 'Kethanoor', null, null),
  (209, 'Thandaar, Neer kondaar, Nambooraar, Saandamakkinnar', null, null, 'Mangammal kovil', 'Pulimarathuppalayam', null, null),
  (210, 'Thandu kondaar', 'Tadikonda', 'Vallutla, Peddhabal', 'Kariyamman kovil', 'Peelamedu', null, null),
  (211, 'Thondaar', null, 'Indhall', 'Kaachammal Poochammal kovil', 'Pattanam', 10.9804139, 77.0551872),
  (212, 'Thoodala maartthar', null, 'Ponoori', 'Angaala Parameshwari kovil', 'Sooloor', null, null),
  (213, 'Thookinnar', null, null, 'Rangammal kovil', 'Maniyakaaranpaalayam', 11.0481388, 76.9749196),
  (214, 'Thungaar', null, 'Ayotthi', 'Mangammal kovil', 'Lakshmi nayakkan palayam', null, null),
  (215, 'Uppalaar, Kesaar', null, null, 'Maadhammal Gengammal kovil', 'Sanuppapatti', null, null),
  (216, 'Uppalar', 'Uppala', 'Pamidipalla, Vipparla', 'Maadhammal kovil', 'Kallappaalayam (Periyapatti)', 11.2159662, 78.1470787),
  (217, 'Uppalar, Pyinder Elamaar, Kaalasthriyaar', null, null, 'Rathnalaar kovil', 'Naaranapuram', 10.7018601, 77.382292),
  (218, 'Uppatlar', null, 'Pepallar', 'Ragammal kovil', 'Sulthan pettai', null, null),
  (219, 'Vallabaar', 'Vallabha/Vallabhuni', 'Dharmalla, Ullamala', 'Endammal kovil', 'Mangarasu, Valaiyapalayam', null, null),
  (220, 'Valuveriyaar', 'Valiveru/Valiveti', 'Pamidipalla', 'Ellammal kovil', 'Vijayapuri, Kovilpatti', null, null),
  (221, 'Vattinnar', 'Vatti', 'Thirikorla', 'Devara kovil', 'Agavanayakkan palayam (Kodumudi)', 11.078, 77.883)
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.kulams','id'), (select max(id) from public.kulams));
