// One-off: append kulams 131–221 (from the community list) into kulams.json.
import { readFileSync, writeFileSync } from "node:fs";

const extra = [
  { id: 131, surname: "Paalkudiyaar", house: "Palakurthi", gothram: "Dhaniyakula, Pongu noola", kuladeivam: "Akkammal Nagammal kovil", place: "Ondipudur, Govindapuram" },
  { id: 132, surname: "Pacchalkuriyaar", house: "Bachalakura", gothram: "Vallutla, Marutla, Thoopaali", kuladeivam: "", place: "Kaalapatti" },
  { id: 133, surname: "Pachar", house: "Pacha", gothram: "Pamidipalla, Tatipalla, Paaledi", kuladeivam: "Akkammal kovil", place: "Matthi nayakkan palayam" },
  { id: 134, surname: "Pachar", house: "Pacha", gothram: "Kundhatla", kuladeivam: "Akkammal kovil", place: "Pottiyampalayam" },
  { id: 135, surname: "Pahaar", house: "", gothram: "Kundhatla", kuladeivam: "Rangammal kovil", place: "Guruvappa naayakkanoor" },
  { id: 136, surname: "Pahaar", house: "Mkullu", gothram: "Kundhatla", kuladeivam: "Thirupathi nayudu endammal kovil", place: "Rajapalayam, chinnakalaiyamuthoor" },
  { id: 137, surname: "Pairpindiyaar", house: "", gothram: "Kandhumadi", kuladeivam: "Mangalagiri ammal kovil", place: "Anuppapatti" },
  { id: 138, surname: "Pandiyaar", house: "Bandi", gothram: "Vallutla, Marutla, Thaaloori", kuladeivam: "Chithammal Nayudu, Polammal kovil", place: "Thandukaranpalayam, Sevoor" },
  { id: 139, surname: "Pangaar", house: "Panga", gothram: "Pamidipalla, Simakurthi, Sri bala", kuladeivam: "Mangammal, Venugopalsaamy nayudu kondammal kovil", place: "Vellamadei" },
  { id: 140, surname: "Pangullar", house: "Panguluri", gothram: "Kundurthi, Pongu noola", kuladeivam: "Devara kovil", place: "Therapaadi" },
  { id: 141, surname: "Parimaar", house: "Parimi", gothram: "Vallutla, Vipparla, Sirumulla", kuladeivam: "Gangammal kovil", place: "Vandara chinnappatti, Gandipatti kottei" },
  { id: 142, surname: "Pathi pattiyar", house: "Pathipati", gothram: "Vipparla, Vemunulla, Namagiri", kuladeivam: "Endammal kovil", place: "Pongaloor" },
  { id: 143, surname: "Pathipatiyaar", house: "Pathipati", gothram: "Vemunulla, Vippattula, Korapati", kuladeivam: "Chithammal kovil", place: "Dhasarapatti" },
  { id: 144, surname: "Pattaar", house: "Batta", gothram: "Tanguturu", kuladeivam: "Devara kovil", place: "Vallappampatti" },
  { id: 145, surname: "Pedda megalaar", house: "", gothram: "", kuladeivam: "Devara kovil", place: "Aandipatti (Paramathi Veloor)" },
  { id: 146, surname: "Pellamma", house: "Bellam", gothram: "Paleti, Paaledi", kuladeivam: "Devara kovil", place: "Eppodhum venraan" },
  { id: 147, surname: "Pepallar", house: "Pepalla", gothram: "Inakandi", kuladeivam: "Ragammal kovil", place: "Poolanginar" },
  { id: 148, surname: "Perugaar", house: "Perugu", gothram: "Daasaraar", kuladeivam: "Endammal kovil", place: "Ramiyampalayam" },
  { id: 149, surname: "Perugaar", house: "Perugu", gothram: "", kuladeivam: "Devara kovil", place: "Pethoindipilla" },
  { id: 150, surname: "Pidikattar", house: "Pidikita", gothram: "Korrapala, Inakandi", kuladeivam: "Chithammal kovil", place: "Ramiyampalayam" },
  { id: 151, surname: "Pikkusennar", house: "", gothram: "", kuladeivam: "Devara kovil", place: "Chinnamettu palayam" },
  { id: 152, surname: "Pikkusennar", house: "", gothram: "", kuladeivam: "Naanammal kovil", place: "Chandrapuram" },
  { id: 153, surname: "Pikkusennar", house: "Bikkasani", gothram: "Jutlunulla, Sootoor", kuladeivam: "Devara kovil", place: "China mettu palayam" },
  { id: 154, surname: "Pikkusennar", house: "Bikkasani", gothram: "", kuladeivam: "Devara kovil", place: "Appanayakkanpatti" },
  { id: 155, surname: "Pindhukondaar", house: "", gothram: "", kuladeivam: "Kommakka kovil", place: "Velliyampalayam" },
  { id: 156, surname: "Pirudhukondaar", house: "Birudukonda", gothram: "Veiloola", kuladeivam: "Bommakka kovil", place: "Kanuvakkarei" },
  { id: 157, surname: "Podhaar", house: "Poda", gothram: "Ullatla", kuladeivam: "Venkitusaami nayudu, endammal kovil", place: "Sikkal noothu" },
  { id: 158, surname: "Polinar", house: "Polina", gothram: "Mandepudi, Mandipidi", kuladeivam: "", place: "" },
  { id: 159, surname: "Pollinnar", house: "Bollina", gothram: "Talluru, Pallanti, Thaatipal", kuladeivam: "Annammal annava nayudu akkammal kovil", place: "Lakshminayakkanpalayam" },
  { id: 160, surname: "Pommamampatti, Sigarpattiyaar", house: "", gothram: "", kuladeivam: "Endammal kovil", place: "Poolanginar" },
  { id: 161, surname: "Pomminnar", house: "Bommineni", gothram: "Talluri", kuladeivam: "Mangammal kovil", place: "Poruloor, Pazhani" },
  { id: 162, surname: "Poodhandiyaar", house: "Pudanti", gothram: "Chennamalla", kuladeivam: "Paradesi Rangammal, Konda Perammal kovil", place: "Devanampalayam" },
  { id: 163, surname: "Poodhantlaar", house: "Poodotha", gothram: "Pannulu, Serukoori", kuladeivam: "Kendaperammal Balarangammal kovil", place: "Devanampaalayam" },
  { id: 164, surname: "Popuraar", house: "Popuri", gothram: "Ullatla", kuladeivam: "Lakshmi ammal kovil", place: "Thottampatti" },
  { id: 165, surname: "Pothillar", house: "Podili", gothram: "Vedanulla, Sri bala", kuladeivam: "Lakshmi kovil", place: "Viyampalayam" },
  { id: 166, surname: "Potla gundaar", house: "Botlagunta", gothram: "Sri bala", kuladeivam: "Ellammal kovil", place: "Ellappa nayakkanoor" },
  { id: 167, surname: "Puliyaar", house: "Puli", gothram: "Sandrolla, Eetha mokkala", kuladeivam: "Dhavathi amman kovil", place: "Pazhani akkarapatti" },
  { id: 168, surname: "Purrar", house: "Puri", gothram: "Sannapuri, Maaratla", kuladeivam: "Devara kovil", place: "Purra nayakkanoor (Koomboor, Vedachandoor)" },
  { id: 169, surname: "Puttar", house: "", gothram: "", kuladeivam: "Devara kovil", place: "Chandirapatti (Kovilpatti)" },
  { id: 170, surname: "Puttar", house: "Putta", gothram: "Inakanti, Dharanipala, Inakandi", kuladeivam: "Nagammal kovil", place: "Nettipatti" },
  { id: 171, surname: "Raaver", house: "Ravuri", gothram: "Guntur, Chennamalla, Pamidipalla", kuladeivam: "Errammal kovil", place: "Devarajapattanam (Kundadam), Tharapuram" },
  { id: 172, surname: "Raayaar", house: "", gothram: "Muppalla, Vallutla", kuladeivam: "Errammal kovil", place: "Karappaadi" },
  { id: 173, surname: "Raayaar", house: "", gothram: "", kuladeivam: "Devara kovil", place: "Kalaiya muthoor" },
  { id: 174, surname: "Raayaar", house: "", gothram: "Kunugu noola", kuladeivam: "Errammal kovil", place: "R.veloor" },
  { id: 175, surname: "Raja kondalaar", house: "", gothram: "Pepalla", kuladeivam: "Mathammal Govindhammal kovil", place: "Panniimadei" },
  { id: 176, surname: "Raja kondalaar", house: "", gothram: "", kuladeivam: "Devara kovil", place: "Athipaalayam" },
  { id: 177, surname: "Raja kondalaar", house: "Rasakondala", gothram: "Pepalla", kuladeivam: "Mathammal Govindhammal kovil", place: "Pannimadei" },
  { id: 178, surname: "Ramaar", house: "Rama", gothram: "Kandanulla, Pasupu noola", kuladeivam: "Akkammal kovil", place: "Veeriyampaalayam" },
  { id: 179, surname: "Rathnaalaar", house: "Ratnala", gothram: "Srilakshmi, Erpell", kuladeivam: "Naanammal kovil", place: "Nagamanaayakkan palayam, Pattanam" },
  { id: 180, surname: "(Common) Renuka Devi", house: "", gothram: "", kuladeivam: "Renuka Devi kovil", place: "Jothipuram" },
  { id: 181, surname: "Saakinnar", house: "Sakineni", gothram: "Vipparla, Ipparali", kuladeivam: "Endammal kovil", place: "Varakuttapalayam" },
  { id: 182, surname: "Sakthi reddyar", house: "", gothram: "Ullamala", kuladeivam: "Lakshmi ammal kovil", place: "" },
  { id: 183, surname: "Sallar", house: "Sallapaneni", gothram: "Recherla, Aranoori", kuladeivam: "Gengammal kovil", place: "Murungappatti" },
  { id: 184, surname: "Sallkundaar", house: "Sallagundla", gothram: "Parishpalla", kuladeivam: "Devara kovil", place: "Guruvappa Naayakkanoor, Naarapatti" },
  { id: 185, surname: "Sammebaar", house: "Sammeta", gothram: "Vallutla", kuladeivam: "Devi kovil", place: "Lakshmipuram" },
  { id: 186, surname: "Sappatiyaar", house: "Sappidi", gothram: "Kancherla, Pulikorla", kuladeivam: "Lingammal kovil", place: "Vaazhavaadi" },
  { id: 187, surname: "Sappitiyaar", house: "Kudipayinda", gothram: "Paidipala, Paindibal", kuladeivam: "Ayilammal kovil", place: "China Vaazhapaadi" },
  { id: 188, surname: "Sappitiyaar", house: "Sappidi", gothram: "Puligorla, Payindibal", kuladeivam: "Thaathan kovil", place: "Kavundanpaalayam" },
  { id: 189, surname: "Saripinnar", house: "Sariputi", gothram: "Avapuru, Aavulpuli", kuladeivam: "Lakshmi Ammal Kovil", place: "Aavarampalayam" },
  { id: 190, surname: "Seekaar", house: "Seku", gothram: "Pongu noola", kuladeivam: "Akkammal kovil", place: "Valiyapalayam" },
  { id: 191, surname: "Seemattakaangallar", house: "", gothram: "", kuladeivam: "Akkammal kovil", place: "Poolvaadi, Rangasamuthiram" },
  { id: 192, surname: "Seethaar", house: "", gothram: "Adhuku noola", kuladeivam: "Akkammal kovil", place: "Veloor" },
  { id: 193, surname: "Semaar", house: "", gothram: "Sirumulla", kuladeivam: "Guruvammal / Devara kovil", place: "Pongaloor; Manjekavundan Pudhoor" },
  { id: 194, surname: "Sennar", house: "", gothram: "Pasupunulla", kuladeivam: "Thathan koil, Konammal kovil", place: "Kavundanpaalayam, Modakkupati" },
  { id: 195, surname: "Sennar, Namboraar, Thookinaar", house: "", gothram: "", kuladeivam: "Rayar kaatupillar kovil", place: "Periyanayakkanpalayam" },
  { id: 196, surname: "Serukkooraar", house: "Cherukuri", gothram: "Marutla, Ullatla, Maaramala", kuladeivam: "Devara kovil", place: "Kundavalasu; Narasingaapuram, Aravakkurichi" },
  { id: 197, surname: "Sigarpattiyar", house: "Sigarapati", gothram: "Kanoor", kuladeivam: "Rangammal kovil", place: "Moolakkurumba paalayam" },
  { id: 198, surname: "Sigarpattiyar", house: "Sigarapati/Chigurupati", gothram: "Kanumanulla, Karumpoori", kuladeivam: "Sooramal kovil", place: "Sallaarapalayam" },
  { id: 199, surname: "Sivattakaangallar", house: "", gothram: "", kuladeivam: "Akkammal kovil", place: "Adivalli" },
  { id: 200, surname: "Sooriya kondalaar", house: "Suryakondala", gothram: "", kuladeivam: "Kondammal kovil", place: "Ravanavapuram" },
  { id: 201, surname: "Sovinnar", house: "", gothram: "Ullatla", kuladeivam: "Rangammal kovil", place: "Manjuvalli" },
  { id: 202, surname: "Sungarar", house: "Sunkara", gothram: "Marutla, Vipparla", kuladeivam: "Unnal kovil", place: "Thalijallipatti" },
  { id: 203, surname: "Sunjaar", house: "", gothram: "Maaratla", kuladeivam: "Endammal kovil", place: "Karadivaavi" },
  { id: 204, surname: "Thaalraar", house: "Talluri", gothram: "", kuladeivam: "Poodhaatiyaar kovil", place: "Komangalam" },
  { id: 205, surname: "Thaavullar", house: "Davuluri", gothram: "Cherukunulla, Serukkoori", kuladeivam: "Rangammal lakshmiyammal kovil", place: "Sikkalnoothu" },
  { id: 206, surname: "Thakkupattiyar", house: "Daggubati", gothram: "Srikanta, Eendham kola", kuladeivam: "Rangammal lakshmiyammal kovil", place: "Sikkalnoothu" },
  { id: 207, surname: "Thamminnar", house: "Thammina/Thammineni", gothram: "Mallepuvvula, Prepala, Tritaloka, Thinoolla", kuladeivam: "Chithammal nayudu, Polammal kovil", place: "Thandukaranpalayam, Sevoor" },
  { id: 208, surname: "Thandaar", house: "Thandra", gothram: "Cherukupalla, Pulikorlu", kuladeivam: "", place: "Kethanoor" },
  { id: 209, surname: "Thandaar, Neer kondaar, Nambooraar, Saandamakkinnar", house: "", gothram: "", kuladeivam: "Mangammal kovil", place: "Pulimarathuppalayam" },
  { id: 210, surname: "Thandu kondaar", house: "Tadikonda", gothram: "Vallutla, Peddhabal", kuladeivam: "Kariyamman kovil", place: "Peelamedu" },
  { id: 211, surname: "Thondaar", house: "", gothram: "Indhall", kuladeivam: "Kaachammal Poochammal kovil", place: "Pattanam" },
  { id: 212, surname: "Thoodala maartthar", house: "", gothram: "Ponoori", kuladeivam: "Angaala Parameshwari kovil", place: "Sooloor" },
  { id: 213, surname: "Thookinnar", house: "", gothram: "", kuladeivam: "Rangammal kovil", place: "Maniyakaaranpaalayam" },
  { id: 214, surname: "Thungaar", house: "", gothram: "Ayotthi", kuladeivam: "Mangammal kovil", place: "Lakshmi nayakkan palayam" },
  { id: 215, surname: "Uppalaar, Kesaar", house: "", gothram: "", kuladeivam: "Maadhammal Gengammal kovil", place: "Sanuppapatti" },
  { id: 216, surname: "Uppalar", house: "Uppala", gothram: "Pamidipalla, Vipparla", kuladeivam: "Maadhammal kovil", place: "Kallappaalayam (Periyapatti)" },
  { id: 217, surname: "Uppalar, Pyinder Elamaar, Kaalasthriyaar", house: "", gothram: "", kuladeivam: "Rathnalaar kovil", place: "Naaranapuram" },
  { id: 218, surname: "Uppatlar", house: "", gothram: "Pepallar", kuladeivam: "Ragammal kovil", place: "Sulthan pettai" },
  { id: 219, surname: "Vallabaar", house: "Vallabha/Vallabhuni", gothram: "Dharmalla, Ullamala", kuladeivam: "Endammal kovil", place: "Mangarasu, Valaiyapalayam" },
  { id: 220, surname: "Valuveriyaar", house: "Valiveru/Valiveti", gothram: "Pamidipalla", kuladeivam: "Ellammal kovil", place: "Vijayapuri, Kovilpatti" },
  { id: 221, surname: "Vattinnar", house: "Vatti", gothram: "Thirikorla", kuladeivam: "Devara kovil", place: "Agavanayakkan palayam (Kodumudi)" },
];

const rows = JSON.parse(readFileSync("data/kulams.json"));
const have = new Set(rows.map((r) => r.id));
let added = 0;
for (const e of extra) {
  if (!have.has(e.id)) { rows.push(e); added++; }
}
rows.sort((a, b) => a.id - b.id);
writeFileSync("data/kulams.json", JSON.stringify(rows, null, 2) + "\n");
console.log(`Appended ${added}. Total now ${rows.length}.`);
